/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.e.home_pro;

/**
 *
 * @author ahmed
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        //txtusername.setBack
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtusernamebox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpasswordbox = new javax.swing.JPasswordField();
        cancelbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        txtforgetpass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        checkboxbtn = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Home Pro");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMaximizedBounds(new java.awt.Rectangle(640, 480, 480, 480));
        setMaximumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Leelawadee", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME / EMAIL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        txtusernamebox.setBackground(java.awt.Color.lightGray);
        getContentPane().add(txtusernamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 230, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Don't have any account? Try ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 180, 20));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        txtpasswordbox.setBackground(java.awt.Color.lightGray);
        txtpasswordbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpasswordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordboxActionPerformed(evt);
            }
        });
        getContentPane().add(txtpasswordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 230, 30));

        cancelbtn.setBackground(new java.awt.Color(153, 153, 153));
        cancelbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        loginbtn.setBackground(new java.awt.Color(239, 107, 72));
        loginbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        txtforgetpass.setForeground(new java.awt.Color(255, 255, 255));
        txtforgetpass.setText("Forget Password?");
        getContentPane().add(txtforgetpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setLabel("Sign-Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, 20));

        jButton2.setBackground(new java.awt.Color(192, 192, 192));
        jButton2.setText("Log in with Google");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 160, 20));

        checkboxbtn.setBackground(new java.awt.Color(72, 78, 111));
        checkboxbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkboxbtn.setText("Remember me");
        checkboxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxbtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkboxbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ahmed\\Downloads\\login (Small).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void txtpasswordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void checkboxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JCheckBox checkboxbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel txtforgetpass;
    private javax.swing.JPasswordField txtpasswordbox;
    private javax.swing.JTextField txtusernamebox;
    // End of variables declaration//GEN-END:variables
}
